# profile??
spring:
  profiles:
    default: test
    active: prod
  # ?? jpa ??
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect